// Generated by CoffeeScript 1.9.1
(function() {
  var highlightJsPlugin;

  highlightJsPlugin = function() {
    (function() {
      var element, hljs_nodes, i, len, results;
      if (typeof window.addEventListener === "function") {
        hljs_nodes = document.querySelectorAll("pre code");
        i = 0;
        len = hljs_nodes.length;
        results = [];
        while (i < len) {
          element = hljs_nodes[i];
          if (element.hasAttribute("data-trim") && typeof element.innerHTML.trim === "function") {
            element.innerHTML = element.innerHTML.trim();
          }
          element.innerHTML = element.innerHTML.replace(/</g, "&lt;").replace(/>/g, "&gt;");
          element.addEventListener("focusout", function(event) {
            return hljs.highlightBlock(event.currentTarget);
          }, false);
          results.push(i++);
        }
        return results;
      }
    })();
    return hljs.initHighlightingOnLoad();
  };

  head.js("vendor/zepto.js", "node_modules/marked/marked.min.js", "scripts/preso.js", function() {
    var p;
    p = new Preso();
    Reveal.initialize({
      controls: false,
      progress: true,
      history: true,
      keyboard: true,
      loop: false,
      mouseWheel: false,
      rollingLinks: false,
      theme: "simple",
      transition: "none",
      dependencies: [
        {
          src: "reveal.js/lib/js/classList.js",
          condition: function() {
            return !document.body.classList;
          }
        }, {
          src: "vendor/highlight.js/highlight.pack.js",
          async: true,
          callback: highlightJsPlugin
        }
      ]
    });
    return Reveal.addEventListener("slidechanged", function() {
      var current_slide;
      return current_slide = $(".present")[0];
    });
  });

}).call(this);
